### ISSUE TITLE
docker-compose version 2.1 (v2.1)

### ISSUE THREAD

**Issue by vito-c** [docker/libcompose#441]
I just changed the version from:
```
version: '2'
services:
```
to
```
version: '2.1'
services:
```
and  I get the following error:
```
ERRO[0000] Could not parse config for project libcompose : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2.1` into config.RawService
panic: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2.1` into config.RawService
```

Are there plans to support version 2.1 in the future? There are some important features added to the compose file `healthcheck` and `depends_on` was improved.

**Comment by vdemeester** [comment]
@vito-c yes there is 👼 Just lagging behind quite a bit (running a little bit out of time 😅)

**Comment by vito-c** [comment]
I would love to help is there a branch? or does it need to be implemented from scratch?

**Comment by vito-c** [comment]
@vdemeester anything I can do to help?

**Comment by joshwget** [comment]
It sounds like the changes to `depends_on` aren't supported in v3 anymore (https://github.com/docker/compose/blob/master/CHANGELOG.md#compose-file-version-21-and-up). Is it worth working on this feature still?

**Comment by vito-c** [comment]
@joshwget backwards compatibility is important.

I'm also a little confused by the decision to drop support for `depends_on` and `health_checks` I haven't really heard a good argument for doing so.

**Comment by yelvert** [comment]
+1

**Comment by cheapRoc** [comment]
I've [started working](https://github.com/cheapRoc/libcompose/commits/refactor-v2_1) on some of this in my spare time. I'm not 100% positive why the changes were made in [this commit](https://github.com/docker/libcompose/commit/99e58bed93c224d4cc7f49a1a643e5854094155f) but I've got past the general YAML parsing error mentioned in this issue simply by removing some unused portion of that commit (there's a double YAML parse within `CreateConfig`).

In order to begin the support of more compose file versions (#474, #490) I hope to continue refactoring between when the compose file is parsed and when it is validated by JSON schema. I think that should at least bump this up to '2.1'. 

I'll try to post something up early to see what the original authors think. Cheers.

**Comment by joyel24** [comment]
+1 for support 2.1 yml

**Comment by mlosev** [comment]
I think we also need 2.2 schema support

**Comment by donbobka** [comment]
+1 version 2.3

**Comment by lpalgarvio** [comment]
https://github.com/rancher/rancher/issues/10158

**Comment by CpuID** [comment]
Good to close thanks to https://github.com/docker/libcompose/pull/507 (I think).
